version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
